services:
  - type: web
    name: keiziban-yukibbs-mintia-ama0507-bbs-yuki-renban-seisei
    env: python
    region: Oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn --port $PORT --host 0.0.0.0 main:app"
